initial gameboard
haydenrust1/Jeopardize pull request #13
Opened 2020-10-22 02:28 UTC by HumbleKind

2020-10-22 02:30 UTC, HumbleKind commented
set /index route to render jeopardyBoard.handlebars view (Stevi's initial board)

2020-10-22 03:07 UTC, haydenrust1 requested changes
keep index on file 26 of the html routes file.  the 'jeopardyBoard' handlebar file is called on line 31 already!

2020-10-22 20:51 UTC, haydenrust1 requested changes
Looks great, but lines 4-13 on questions.js are commented out! please uncomment those and we will be good :)

2020-10-23 01:49 UTC, haydenrust1 approved these changes

2020-10-23 01:50 UTC, merged